In [2]:
import pandas as pd

names =['timestamp', 'activityID', 'heartrate', 'IMUH_temp', 'IMUH_acc1', 'IMUH_acc2',
              'IMUH_acc3', 'IMUH_acc1_6g', 'IMUH_acc2_6g', 'IMUH_acc3_6g', 'IMUH_gyr1', 'IMUH_gyr2', 'IMUH_gyr3',
              'IMUH_mag1', 'IMUH_mag2', 'IMUH_mag3', 'IMUH_orientation1', 'IMUH_orientation2', 'IMUH_orientation3',
             'IMUH_orientation4', 'IMUC_temp', 'IMUC_acc1', 'IMUC_acc2', 'IMUC_acc3', 'IMUC_acc1_6g', 'IMUC_acc2_6g', 
             'IMUC_acc3_6g', 'IMUC_gyr1', 'IMUC_gyr2', 'IMUC_gyr3', 'IMUC_mag1', 'IMUC_mag2', 'IMUC_mag3', 
             'IMUC_orientation1', 'IMUC_orientation2', 'IMUC_orientation3', 'IMUC_orientation4', 'IMUA_temp', 
             'IMUA_acc1', 'IMUA_acc2', 'IMUA_acc3', 'IMUA_acc1_6g', 'IMUA_acc2_6g', 'IMUA_acc3_6g', 'IMUA_gyr1', 
             'IMUA_gyr2', 'IMUA_gyr3', 'IMUA_mag1', 'IMUA_mag2', 'IMUA_mag3', 'IMUA_orientation1', 'IMUA_orientation2', 
             'IMUA_orientation3', 'IMUA_orientation4', 'subjectID']
df = pd.DataFrame(columns=names)
for i in range(101,110) :

    df_temp = pd.read_csv('PAMAP2_Dataset/Protocol/subject'+ str(i)+'.dat', sep=" ",header=None, names=names)
    df_temp['subjectID'] = 'subject' + str(i)
    df = pd.concat([df, df_temp], ignore_index=True)

In [11]:
df_sj = pd.read_csv('PAMAP2_Dataset/Protocol/subject101.dat', sep=" ",header=None, names=names)

#minimum and max values of timestamp
df_sj['timestamp'].min(), df_sj['timestamp'].max()

(8.38, 3772.54)

In [3]:
df.head()

,timestamp,activityID,heartrate,IMUH_temp,IMUH_acc1,IMUH_acc2,IMUH_acc3,IMUH_acc1_6g,IMUH_acc2_6g,IMUH_acc3_6g,...,IMUA_gyr2,IMUA_gyr3,IMUA_mag1,IMUA_mag2,IMUA_mag3,IMUA_orientation1,IMUA_orientation2,IMUA_orientation3,IMUA_orientation4,subjectID
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0,subject101
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0,subject101
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0,subject101
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0,subject101
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0,subject101

In [4]:
df.shape

(2872533, 55)

In [5]:
# resetting dataframe index

df = df.reset_index()

In [6]:
df

,index,timestamp,activityID,heartrate,IMUH_temp,IMUH_acc1,IMUH_acc2,IMUH_acc3,IMUH_acc1_6g,IMUH_acc2_6g,...,IMUA_gyr2,IMUA_gyr3,IMUA_mag1,IMUA_mag2,IMUA_mag3,IMUA_orientation1,IMUA_orientation2,IMUA_orientation3,IMUA_orientation4,subjectID
0,0,8.38,0,104.0,30.0000,2.37223,8.60074,3.51048,2.43954,8.76165,...,0.009250,-0.017580,-61.1888,-38.95990,-58.143800,1.000000,0.000000,0.000000,0.000000,subject101
1,1,8.39,0,NaN,30.0000,2.18837,8.56560,3.66179,2.39494,8.55081,...,-0.004638,0.000368,-59.8479,-38.89190,-58.525300,1.000000,0.000000,0.000000,0.000000,subject101
2,2,8.40,0,NaN,30.0000,2.37357,8.60107,3.54898,2.30514,8.53644,...,0.000148,0.022495,-60.7361,-39.41380,-58.399900,1.000000,0.000000,0.000000,0.000000,subject101
3,3,8.41,0,NaN,30.0000,2.07473,8.52853,3.66021,2.33528,8.53622,...,-0.020301,0.011275,-60.4091,-38.76350,-58.395600,1.000000,0.000000,0.000000,0.000000,subject101
4,4,8.42,0,NaN,30.0000,2.22936,8.83122,3.70000,2.23055,8.59741,...,-0.014303,-0.002823,-61.5199,-39.38790,-58.269400,1.000000,0.000000,0.000000,0.000000,subject101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,2872528,100.19,0,NaN,25.1875,-4.71493,10.22250,4.66893,-5.04654,9.94944,...,-0.062676,-0.127084,-46.5153,3.58240,-0.035995,0.598531,0.033615,0.799791,-0.031075,subject109
2872529,2872529,100.20,0,NaN,25.1875,-4.95932,10.37130,4.12594,-4.96890,10.29620,...,-0.027006,-0.089808,-45.7474,3.54453,0.108583,0.598428,0.033012,0.799933,-0.030018,subject109
2872530,2872530,100.21,0,NaN,25.1875,-4.93997,9.83615,3.70468,-5.04613,10.35690,...,-0.038024,-0.064709,-46.3997,4.22078,0.105504,0.598233,0.033172,0.800095,-0.029416,subject109
2872531,2872531,100.22,0,NaN,25.1875,-4.64941,9.11129,3.51904,-5.06854,9.75268,...,-0.025796,-0.064357,-46.5282,4.48593,0.530240,0.598116,0.033427,0.800180,-0.029208,subject109
2872532,2872532,100.23,0,161.0,25.1875,-4.09726,8.15642,3.29961,-4.73244,8.82870,...,0.011866,-0.042858,-46.2704,4.21475,0.247798,0.598119,0.033685,0.800188,-0.028602,subject109

In [8]:
df.drop(['index'], axis=1, inplace = True)

In [37]:
df

,timestamp,activityID,heartrate,IMUH_temp,IMUH_acc1,IMUH_acc2,IMUH_acc3,IMUH_acc1_6g,IMUH_acc2_6g,IMUH_acc3_6g,...,IMUA_gyr2,IMUA_gyr3,IMUA_mag1,IMUA_mag2,IMUA_mag3,IMUA_orientation1,IMUA_orientation2,IMUA_orientation3,IMUA_orientation4,subjectID
0,8.38,0,104.0,30.0000,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.009250,-0.017580,-61.1888,-38.95990,-58.143800,1.000000,0.000000,0.000000,0.000000,subject101
1,8.39,0,NaN,30.0000,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.004638,0.000368,-59.8479,-38.89190,-58.525300,1.000000,0.000000,0.000000,0.000000,subject101
2,8.40,0,NaN,30.0000,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.000148,0.022495,-60.7361,-39.41380,-58.399900,1.000000,0.000000,0.000000,0.000000,subject101
3,8.41,0,NaN,30.0000,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,-0.020301,0.011275,-60.4091,-38.76350,-58.395600,1.000000,0.000000,0.000000,0.000000,subject101
4,8.42,0,NaN,30.0000,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,-0.014303,-0.002823,-61.5199,-39.38790,-58.269400,1.000000,0.000000,0.000000,0.000000,subject101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,100.19,0,NaN,25.1875,-4.71493,10.22250,4.66893,-5.04654,9.94944,4.50736,...,-0.062676,-0.127084,-46.5153,3.58240,-0.035995,0.598531,0.033615,0.799791,-0.031075,subject109
2872529,100.20,0,NaN,25.1875,-4.95932,10.37130,4.12594,-4.96890,10.29620,4.43102,...,-0.027006,-0.089808,-45.7474,3.54453,0.108583,0.598428,0.033012,0.799933,-0.030018,subject109
2872530,100.21,0,NaN,25.1875,-4.93997,9.83615,3.70468,-5.04613,10.35690,4.14405,...,-0.038024,-0.064709,-46.3997,4.22078,0.105504,0.598233,0.033172,0.800095,-0.029416,subject109
2872531,100.22,0,NaN,25.1875,-4.64941,9.11129,3.51904,-5.06854,9.75268,3.87359,...,-0.025796,-0.064357,-46.5282,4.48593,0.530240,0.598116,0.033427,0.800180,-0.029208,subject109
2872532,100.23,0,161.0,25.1875,-4.09726,8.15642,3.29961,-4.73244,8.82870,3.54305,...,0.011866,-0.042858,-46.2704,4.21475,0.247798,0.598119,0.033685,0.800188,-0.028602,subject109

In [12]:
df['activityID'].value_counts()

0     929661
4     238761
17    238690
1     192523
3     189931
7     188107
2     185188
16    175353
6     164600
12    117216
13    104944
5      98199
24     49360
Name: activityID, dtype: int64

In [14]:
df.to_csv('processed_data/HAR.csv', encoding='utf-8', index=False, header=True)